server:
  port: 8183
  servlet:
    context-path: /elastic-query-serivce

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

# [zeev@localhost ~]$ spring decrypt baeb90d57edb9a050b97b98a7d8cabe80ee884e6fff16c22956172459a43e54d --key 'Demo_Pwd!2020'
# test1234
user-config:
  username: test
  password: '{cipher}baeb90d57edb9a050b97b98a7d8cabe80ee884e6fff16c22956172459a43e54d'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs